### ISSUE TITLE
Help with implimenting the FFMPEG stream on a Windows machine using VLC?

### ISSUE THREAD

**Issue by Kalp0101** [25nlambert/BOREALIS_Cam#3]
As the title states, I want help displaying the stream on a Windows machine. In "Usage/Examples" under the pi5 repo, you recommend using Linux but is it possible to do it on Windows instead? I've been having no luck trying to run it in VLC on Windows.

**Comment by 25nlambert** [comment]
Hello! Yes, you should be able to do it with Windows. We created documentation in a Google Doc, but it doesn't look like we directly attached it to this repository. I can update that. Additionally, here is the link for the time being https://docs.google.com/document/d/1IDkR-tbgngC3c4e2qKCqgqcCxsmayxmprr62sG7MYJM/edit?usp=sharing

I hope this solves your issue, if not, let me know here and I will do my best to help out :)

**Comment by Kalp0101** [comment]
I followed the instructions on the Google Doc and ran
`ffplay -fflags nobuffer udp://192.168.2.23:8554`
In the command terminal on my Windows-based ground station computer. It seems to run part of the command but doesn't do anything after a certain point. I've attached an image showing what cmd displays and gets stuck on after I run the command:

<img width="863" alt="image" src="https://github.com/user-attachments/assets/589956ad-ad42-44b9-88b7-f89a509cde21">


Do you know what could be causing this issue?

**Comment by 25nlambert** [comment]
I would try to see if you are actually able to communicate with your Pi, so in the terminal, you can do "ping 192.168.2.23" and it should tell you that it is either receiving a reply or it is not able to communicate.

**Comment by Kalp0101** [comment]
I'm getting 100% loss when trying to Ping, does this mean it's a problem with the Pi's connection?

**Comment by 25nlambert** [comment]
I believe so yes. For some reason or another your laptop isn't able to talk to your Pi. Can you give me a run down of how you have everything connected related to the Ubiquiti rockets and Ethernet cables etc.?

**Comment by Kalp0101** [comment]
Yeah! I figured it would be easiest to show you through pictures:

Payload:
![PXL_20240723_191409716 MP](https://github.com/user-attachments/assets/f65a828c-7596-4b37-a0ed-a3881f8fc567)

Ground Station:
![PXL_20240723_191528167](https://github.com/user-attachments/assets/77609496-2b9c-4d9c-a837-11629a96a19d)

**Comment by 25nlambert** [comment]
Hmm, everything looks right, assuming that the blue Ethernet cable is plugged into the back of the laptop as I can't see it. 

My next course of action would be to turn off the wifi on the laptop and then running "ipconfig /all" in the terminal. This is to verify that your laptop is running on the correct subnet.

Additionally, if you are able to connect a monitor to your pi and running "ifconfig" in a terminal on your Pi to verify that it has been setup with the correct subnet as well.

Note: it is "ipconfig" for windows and "ifconfig" for Linux, not a spelling mistake.

The subnet is the third octet in the IP address 
192.168.X.23 where the X is the subnet. These should be matching.

**Comment by Kalp0101** [comment]
I see, is the circled number (from the Pi terminal) in the image below correct?
![PXL_20240723_193900339~2](https://github.com/user-attachments/assets/68cc49f5-253c-4728-84ce-e938c0109224)

It it normal for the subnet to be a number besides 1 or 2?

**Comment by 25nlambert** [comment]
In most small and or home networks, it is typically a 1 or 2. But typically it doesn't matter what that number is as long as all your devices that you want to talk to have it as the same number. Is it 137 for your laptop too?

**Comment by 25nlambert** [comment]
Additionally, part of the reason that you could not get video or ping your Pi is because the address that you were typing in to receive video in VLC or ffmpeg is not the same. Essentially you're knocking on the wrong house, if that makes sense.

**Comment by Kalp0101** [comment]
I did some messing around on the ground station laptop to get it to match the subnet of the Pi (It was different before). I went to network connections and set up a static ip using the same subnet as the Pi but I'm still running into the same problem. To answer the other part, I haven't been using VLC for any of the steps yet and it isn't strictly necessary to use VLC because that was just what our YouTube streaming had overlays for. They could easily be shifted over if VLC wouldn't work for this set-up.

**Comment by Kalp0101** [comment]
Another thing, I ran the ping command you mentioned earlier, and I now have 0% loss! I still cannot run the stream though.

**Comment by 25nlambert** [comment]
Great! One step closer. 

The next thing I would do is check the Pi to see if it's actually trying to stream something. This can be checked using
"systemctl status BOREALIS_CAM0.service" on the Pi

Just curious, did you use the install command when installing this on the Pi?

**Comment by Kalp0101** [comment]
I ran the BOREALIS_CAM command on the Pi and it's telling me that it is enabled and running.
As for whether I used the install, I ran this command on the Pi:
`cd
bash <(sudo curl -SL https://shorturl.at/jnEM9)`
As mentioned in the Doc. Maybe the IP address I inputted when installing doesn't work anymore because I changed the static IP on my ground station computer?

**Comment by 25nlambert** [comment]
That could be the issue if you changed it after the fact.

So have you tried it with the new IP address of the Pi?

**Comment by Kalp0101** [comment]
I'm continuing working on this tomorrow, but when I want to change the ground station IP that I input on the PI, what command should I run?

**Comment by 25nlambert** [comment]
You should run the installation command again, it will bring up the configuration screen again.

**Comment by Kalp0101** [comment]
I ran the installation command and set it up using the new configuration, and I'm still able to ping with 0 loss between the two devices. Unfortunately, running the ffplay script in the windows terminal still gives me the same issue. Here's a screenshot of what it shows me if you can diagnose it.

<img width="960" alt="image(1)" src="https://github.com/user-attachments/assets/48410242-9a8f-4c71-bd56-365bfa5b4706">

It just stays like that and doesn't change

**Comment by 25nlambert** [comment]
That is odd. If you were to run the ffplay command on the Pi itself plugged into a monitor, does it do the same thing?

**Comment by Kalp0101** [comment]
Sure enough, it does the same thing when run on the Pi. 
Side question, if this is to work as intended, should there just be a pop-up with a video feed or am I missing a step after running the ffplay script?

**Comment by 25nlambert** [comment]
There won't be a pop up or anything as a means of reducing the power consumption. But if you are trying to watch the stream, it should show up. 

One thing that I was told was you could replace the IP "192.168....23" with "localhost" to get the stream right inside of the pi. This will be done on the Pi, if that isn't working, there might be another issue, it is possible that the Pi is struggling to get a feed from the cameras.

If you run these two commands, it should show you if it is detecting the cameras on the Pi

`sudo systemctl stop BOREALIS_CAM0.service BOREALIS_CAM1.service`
`raspicam-hello --list-camera`

**Comment by 25nlambert** [comment]
![image](https://github.com/user-attachments/assets/8c26dea0-6464-4530-8405-8d6c86eed9d2)

![image](https://github.com/user-attachments/assets/388bb9c1-55b6-4190-8e1e-abbca1f6f55a)

**Comment by Kalp0101** [comment]
I've tested the cameras and they're connected and work properly. I doubt there's a hardware issue as the Ubiquiti radios are also properly connected and work with an older Pi 4 set-up.
Do you think there's a problem with the script I'm running on the GS computer?
`ffplay -fflags nobuffer udp://192.168.2.23:8554`
`ffplay -fflags nobuffer udp://192.168.2.23:8555`
Should a video feed pop up on my laptop after I run the script above? 
Sidenote, I've tried running the script above and a slightly altered version that matches the subnet of the Pi and GS computer
`ffplay -fflags nobuffer udp://192.168.137.23:8554`
`ffplay -fflags nobuffer udp://192.168.137.23:8555`
But this leaves me with the same issues of the terminal just not doing anything.

**Comment by 25nlambert** [comment]
Yes, when the ffplay command is run, it should opens window that displays the camera feed. I am quite puzzled right now. Is there a way that you could share the BOREALIS_Cam folder on the Pi with me? 

So we have checked the wiring, we can communicate with the Pi. It makes me wonder if the configuration files in the BOREALIS_Cam folder are messed up from the installation script. When we first made this, we experienced an issue where that could happen but haven't seen it in a long time.

**Comment by Kalp0101** [comment]
Here's a link to the BOREALIS_Cam folder straight from the Pi:
[[https://drive.google.com/drive/folders/18UzJmjKDyyd126Xhwm-7zMOMTA_2A_1z?usp=sharing](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdrive.google.com%2Fdrive%2Ffolders%2F18UzJmjKDyyd126Xhwm-7zMOMTA_2A_1z%3Fusp%3Dsharing&data=05%7C02%7CKalp.Sandip.Patel%40live.mercer.edu%7C889e65da6b904482e3ae08dcacec1cd6%7C4fb34d2889b247109bcc30824d17fc30%7C0%7C0%7C638575377299415239%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=BufvFlmrBuMmuZbdDcCv27S7jymx%2FtmjH9yrjOG%2FPOE%3D&reserved=0)](url)

**Comment by 25nlambert** [comment]
Thank you for providing that folder for me. Unfortunately I do not have our payload to test this on and am only going off of a visual inspection. Everything looks okay as long as your laptop had it's internal IP address set to 192.168.137.49 . 

If you are not even able to get the video to play on the Pi, I believe it would have to be something related to the service that is running to generate the stream. I had you do this before but only asked to see if it was running and not a detailed view. 

Would you be able to send a picture of the output of running 
`systemctl status BOREALIS_CAM0.service` on the Pi? I am hoping that it can provide some insight into what is happening.

This command also could be useful.
`journalctl -u BOREALIS_CAM0.service`

**Comment by Kalp0101** [comment]
Here are images from the outputs of each of those scripts:
systemctl:
![20240726_132450](https://github.com/user-attachments/assets/4b1ad1f9-52bd-4cc7-bae7-babd735dc85c)

journalctl:
![20240726_132817](https://github.com/user-attachments/assets/70fd8d57-7026-4673-a98a-cd3b98c7b8c4)
![20240726_133821](https://github.com/user-attachments/assets/78d52a42-8a0d-4993-815e-cfc479a24ebe)

This is the last time I'll be able to work on the Pi for the next three weeks. Thanks for the help so far, I look forward to getting this working once I'm back.

**Comment by 25nlambert** [comment]
Thank you for those images, I will look at them and see if I can decipher anything for when you come back!

**Comment by Kalp0101** [comment]
Hello Again! Any updates?

**Comment by 25nlambert** [comment]
Hello!
I have had limited access to a Pi up until recently. From what I have found though is that there is something that changed related to how the Pi software runs which is causing an issue with the IP address output. I am currently reinstalling my image and then attempting to find the change that will fix the issue.

**Comment by 25nlambert** [comment]
I have made a video here
https://youtu.be/ZZvWyN0k0-Q

It is currently processing but should be available very soon.

**Comment by Kalp0101** [comment]
Thanks for the video! I'll try changing the config file and testing the stream sometime later today or tomorrow.

**Comment by Kalp0101** [comment]
Hey, I've been a little busy so I was able to run a quick test today. I ran the cam0_start_stream script and got different errors than the ones you showed in the video:
![PXL_20240828_172706441](https://github.com/user-attachments/assets/d3de79dd-6fc2-4d09-b05b-ce4e6e1b8431)

Do you know what it means by "device or resource busy"? I ran the camera test script to make sure the cameras worked and that doesn't seem to be the issue.

**Comment by 25nlambert** [comment]
When you ran the "bash cam0..." command, did you stop the camera services from running that start at startup?

"sudo systemctl stop BOREALIS_CAM0.service"

When it says that resources are busy, it means that something else is currently using the camera. Things have to take turns unfortunately, but unless something else is running, stopping the service should allow you to access the cameras

**Comment by Kalp0101** [comment]
I've been having issues with power draw with my Pi (insufficient voltage warning on boot-up) because it doesn't seem to get the 5 volts required for it to run. It'll boot up and run but shuts down by itself after being on for a brief amount of time. We use two Blue 10500 mAh, 3.7 V Li-Po batteries so I'll probably be buying new batteries with higher voltages. I'll test what you suggested once those come in. Thanks for all the help so far by the way :)

**Comment by 25nlambert** [comment]
Assuming that you are still using the power board that was provided by Montana in the picture that you posted above (https://github.com/25nlambert/BOREALIS_Cam/issues/3#issuecomment-2246108422), you shouldn't require the need of batteries with a higher voltage to supply the Pi. The power board has a boost converter onboard that will boost the voltage from the battery to the necessary voltage to run the Pi. But if you decide to switch out the batteries to something different, be mindful that the boost converters have a maximum input voltage of 5.5V as noted in the datasheet [https://www.ti.com/lit/ds/symlink/ptn04050c.pdf?ts=1724834630654&ref_url=https%253A%252F%252Feu.mouser.com%252F](url) . 

I recommend making sure that the batteries are fully charged before use. Once you start using them, you should have a comfortable 4 hours of runtime at minimum. It is possible that your batteries have a reduced capacity.

I would also recommend using the Pi power brick to power the Pi and the POE injector to run the Ubiquiti Rocket when doing lab testing such as this troubleshooting. This allows you to run indefinitely on the wall and not worry about how many cycles your batteries have. I am assuming that every team received those items?

One more thing, running on battery will likely give you the following message.
![Screenshot 2024-08-28 at 3 46 50 PM](https://github.com/user-attachments/assets/ec30bab0-05af-44da-a78b-3dba6a73497a)
This is expected because we are powering the Pi by directly bypassing the USB C power circuitry.

You're welcome, keep me posted!

**Comment by Kalp0101** [comment]
Update:

I went back to confirm the subnet of the Ubiquiti and found that it was 1. I then set the static IP on the ground station laptop to `192.168.1.49` (it used to be `192.168.137.49`) as instructed in the Google doc. I ran the install command on the Pi to reconfigure it to the new IP address as well. 

Then, I went into the Pi's network setting and manually set its static IP to `192.168.1.23` because running the `ifconfig` command showed that it still had an IP address of `192.168.137.23` after the configuration. 


I followed the guide you showed in the video and got the following results:

![PXL_20240903_184816586](https://github.com/user-attachments/assets/c51aefaf-c3ee-4699-a9a4-7216576669d5)

Right after, I ran `ffplay -fflags nobuffer udp://192.168.1.23:8554` and `ffplay -fflags nobuffer udp://192.168.1.23:8555` in the ground station laptop's terminal but it led to the same "nan " issue I've had since the beginning. Even when running the command in the Pi's terminal, the same issue persists. I tested to see if ffmpeg was installed correctly, if I could ping the Pi after changing the IP addresses and all of that seems to work without issue.

I think there may be a possibility that something's wrong with the ports in the command?

**Comment by Kalp0101** [comment]
Updates?

**Comment by Kalp0101** [comment]
Good News! It finally works!! The issue turned out to be that I was using an outdated version of Rpi OS. I ran the commands and both streams popped up on my ground station laptop. It's unbelievable that this was the issue all along. Thanks for all your help these past several weeks, and I wish you and University of Maine many great launches!

**Comment by 25nlambert** [comment]
Great! Unfortunately, with school starting recently, it has made my schedule really busy. I am glad that you were able to persist and find the issue. Best of luck to your team as well!
